spring:
  application:
    name: Ssafymarket
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/market?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      platform: mysql
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  # Spring Session 설정 (JDBC 기반)
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout: 1800 # 30분 (초 단위)
    cookie:
      name: SESSION

minio:
  endpoint: ${MINIO_URL}
  access-key: ${MINIO_APP_USER}
  secret-key: ${MINIO_APP_SECRET}
  bucket: ${MINIO_BUCKET}
  secure: false

# 로깅 설정
logging:
  level:
    org.ssafy.ssafymarket: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG

